language: julia
  os:
    - linux
    - osx
  julia:
    - 1.3
    - 1.6


matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
  notifications:
    email: false
  after_success:
  -julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.sumbmit(process_folder())'
  -julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.sumbmit(process_folder())'