language: julia
os:
  - linux
  - osx
julia:
  - 1.3
  - 1.4
  - 1.5
  - 1.6

jobs:
  include:
    - stage: "documentation"
      julia: 1.6
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.add(url="add https://github.com/danphenderson/TRS.jl"); Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip