language: julia
  os:
    - linux
    - osx
  julia:
    - 1.3
    - 1.6
    - nightly
jobs:
  run: julia --project=docs -e '
       using Pkg
       Pkg.add(PackageSpec(url="https://github.com/danphenderson/TRS.jl")) 
       Pkg.develop(PackageSpec(url="https://github.com/danphenderson/BlockOpt.jl"))
       using BlockOpt'

  allow_failures:
    - julia:
      - 1.3
      - 1.6
      - nightly
  fast_finish: true
  notifications:
    email: false
  after_success:
  -julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.sumbmit(process_folder())'
  -julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.sumbmit(process_folder())'